name: Preprocessing-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATASET_PATH: "MLproject/water_potability_preprocessing.csv"
  TARGET_COLUMN: "Potability"
  IMPUTE_METHODE: "median"
  SAVE_PATH: "preprocessor.joblib"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python 3.12.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.11"
      
      # Check file dan env
      - name: Show dataset path
        run: |
          echo "Dataset path: $DATASET_PATH"
          ls -lah MLproject/
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn joblib

      # Run mlflow preprocessing step
      - name: Run mlflow preprocessing
        run: |
          mlflow run . \
            --entry-point main\
            --env-manager=local \
            -p dataset=$DATASET_PATH \
            -p target_column=$TARGET_COLUMN \
            -p impute_method=$IMPUTE_METHODE \
            -p save_path=$SAVE_PATH

      # Save models to Github Repository
      - name: Save mlruns to repository
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add $SAVE_PATH
          git commit -m "Add preprocessor from CI run"
          git push origin main