name: Preprocessing-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATASET_PATH: "water_potability_raw.csv"
  IMPUTE_METHOD: "median"
  SAVE_PATH: "preprocessor.joblib"
  OUTPUT_PATH: "preprocessing/water_potability_preprocessing.csv"

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.11"
      
      # Check dataset info
      - name: Show dataset path
        run: |
          echo "Dataset path: $DATASET_PATH"
          ls -lah .
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas scikit-learn joblib

      # Run mlflow preprocessing step
      - name: Run mlflow preprocessing
        run: |
          mlflow run . \
            --entry-point preprocess \
            --env-manager=local \
            -p dataset=$DATASET_PATH \
            -p impute_method=$IMPUTE_METHOD \
            -p save_path=$SAVE_PATH \
            -p output_path=$OUTPUT_PATH

      # Save models to Github Repository
      - name: Save mlruns to repository
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add $SAVE_PATH $OUTPUT_PATH
          git commit -m "Add preprocessor and cleaned data from CI run"
          git push origin main