name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLproject/water_potability_preprocessing.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Python 3.12.11
      - name: Set up Python 3.12.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.11"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow

      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run MLproject --env-manager=local

      # Save models to Github Repository
      - name: Save mlruns to Repository
        run: |
          git config --global user.name ${{ secrets.username }}
          git config --global user.email ${{ secrets.email }}
          git add mlruns/
          git commit -m "Save mlruns from CI run"
          git push origin master